# Generated by Django 2.0.5 on 2018-05-06 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('streams', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='author',
            new_name='username',
        ),
        migrations.RemoveField(
            model_name='post',
            name='text',
        ),
    ]
