# Generated by Django 2.0.5 on 2018-05-06 20:59

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('streams', '0002_auto_20180506_2058'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post',
            new_name='StreamPost',
        ),
    ]
