# Generated by Django 2.0.5 on 2018-05-06 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streams', '0003_auto_20180506_2059'),
    ]

    operations = [
        migrations.AddField(
            model_name='streampost',
            name='description',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='streampost',
            name='title',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
