# Generated by Django 2.0.5 on 2018-05-06 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('streams', '0004_auto_20180506_2101'),
    ]

    operations = [
        migrations.RenameField(
            model_name='streampost',
            old_name='username',
            new_name='author',
        ),
    ]
