# Generated by Django 2.0.5 on 2018-05-06 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streams', '0005_auto_20180506_2104'),
    ]

    operations = [
        migrations.AddField(
            model_name='streampost',
            name='down_votes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='streampost',
            name='up_votes',
            field=models.IntegerField(default=0),
        ),
    ]
