# Generated by Django 2.0.5 on 2018-05-08 01:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('streams', '0007_auto_20180508_0115'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='streampost',
            name='downvotes',
        ),
        migrations.AddField(
            model_name='streampost',
            name='downvotes',
            field=models.ManyToManyField(blank=True, related_name='downvotes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='streampost',
            name='upvotes',
        ),
        migrations.AddField(
            model_name='streampost',
            name='upvotes',
            field=models.ManyToManyField(blank=True, related_name='upvotes', to=settings.AUTH_USER_MODEL),
        ),
    ]
